# Generated by Django 2.2 on 2022-12-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_visit',
            field=models.BooleanField(default=True),
        ),
    ]
