# Generated by Django 2.2 on 2022-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='anonymous', max_length=40),
        ),
    ]
