# Generated by Django 2.2 on 2022-12-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='handle',
        ),
    ]
