# Generated by Django 2.2 on 2022-12-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default/placeholder.png', upload_to='profile_images'),
        ),
    ]
