# Generated by Django 2.2 on 2022-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20221213_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Tell us something about yourself!'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='friendo', max_length=200),
        ),
    ]
