# Generated by Django 2.2 on 2022-12-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20221213_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='profiles', to='profiles.Hobby'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', to='profiles.Interest'),
        ),
    ]
